title: Sagar Saha
description: PhD in Mathematics | Combinatorial Group Theory
url: https://sagarsahamath.github.io
baseurl: ""

theme: minima

header_pages:
  - research.md
  - publications.md
  - cv.md



author:
  name: Sagar Saha
