title: Sagar Saha
description: PhD in Mathematics | Combinatorial Group Theory
url: https://sagarsahamath.github.io
baseurl: ""

theme: minima

header_pages:
  - research.md
  - publications.md
  - cv.md

plugins:
  - jekyll-scholar

scholar:
  style: plain
  source: ./_bibliography
  bibliography: papers.bib

author:
  name: Sagar Saha
